### ISSUE TITLE
Restructure config/settings/{stage}.yml data

### ISSUE THREAD

**Issue by darrenleeweber** [darrenleeweber/aws-ops#33]
Consider altnernative structure, e.g.
```yaml
zookeeper:
  config:
    {general config settings}

kafka:
  {general kafka settings}

spark:
  {general spark settings}

mesos:
  {general mesos settings}

nodes:
  - node_name:
    - {node settings}
    - services:
      - zookeeper
      - mesos-master

network:
  - security_group_name:
    - {security group settings}
      - services:
        - zookeeper
        - mesos-master

```

Allow the `services` to be an array of services, so that one compute resource (node, network, security group, etc.) can host multiple services.  This can allow co-hosting services, like zookeeper and mesos-master services running on the same node.
Use the keys to find the settings for each service.  The top level key should be the service name.
